scan tickets or provide qrcode manuelly --> ticket-control app
ELITE-Kinoticketsystem/Frontend-KTS pull request #68
Opened 2023-12-18 20:33 UTC by samiri123

- you can test the qrcode scanner by generating QRcode-Strings using online qrcode-generating tools. 
- for now the QRCode must have the following format: **(qrcode 1, qrcode 2 ... qrcode n)** please use this format as string-text to generate qrcode and test the scanner
- later this can be changed to some randome String
- you can also provide qrcode in the above format in the input-field

2023-12-18 20:50 UTC, samiri123 commented
#70

2023-12-19 08:03 UTC, wichijan requested changes

2023-12-19 08:03 UTC, wichijan commented on src/routes/ticketcontrol/+page.svelte
> +                    const movieTitle = `<div>MovieTitle:  ${ticket.movieTitle}</div>`;
here u can use sveltekit real good, and dont need to add them do the container1, with a $: var or with a if condition or smth else

2023-12-19 08:03 UTC, wichijan commented on src/routes/ticketcontrol/+page.svelte
> +    container{
pls use tailwind as we use it everywhere else tailwind is real easy. this would be class="bg-black w-full" for example

2023-12-19 09:12 UTC, samiri123 commented on src/routes/ticketcontrol/+page.svelte
> -                cameraId = devices[0].id;
I changed it to {facingMode: 'environment'}, it works also for webcames

2023-12-19 12:18 UTC, wichijan requested changes
Last fixes then I will merge it

2023-12-19 12:18 UTC, wichijan commented on src/routes/ticketcontrol/+page.svelte
> +    let mauallInput = false;
typo: manualInput

2023-12-19 12:23 UTC, samiri123 commented on src/routes/ticketcontrol/+page.svelte
> +    let mauallInput = false;
typo: check done and corrected

2023-12-19 12:43 UTC, wichijan approved these changes
looks good

2023-12-19 12:43 UTC, merged